# Global default container
container:
  image: wallaroolabs/wallaroo-ci:2018.10.17.1
  cpu: 8
  memory: 24

task:
  name: "build-resilience"
  install_script:
    - .cirrusci/clone_tracker.sh

  test_script:
    - make build-testing-correctness-tests-all resilience=on debug=true

task:
  name: "correctness-tests-resilience"
  depends_on: build-resilience
  test_script:
    - make integration-tests-testing-correctness-tests-all resilience=on debug=true

task:
  name: "build"
  install_script:
    - .cirrusci/clone_tracker.sh

  test_script:
    - make build-testing-correctness-tests-all debug=true

task:
  name: "correctness-tests"
  depends_on: build
  test_script:
    - make integration-tests-testing-correctness-tests-all debug=true
