# Global default container
container:
  image: wallaroolabs/wallaroo-ci:2018.10.17.1
  cpu: 8
  memory: 24

task:
  name: "correctness-tests-resilience"
  install_script:
    - .cirrusci/clone_tracker.sh
  test_script:
    - ulimit -c unlimited
    - ulimit -a
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true resilience=on pytest_exp='-k pony'
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true resilience=on pytest_exp='-k python2'
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true resilience=on pytest_exp='-k python3'
    - make integration-tests-testing-correctness-tests-resilience-all debug=true resilience=on pytest_exp='-k pony'
    - make integration-tests-testing-correctness-tests-resilience-all debug=true resilience=on pytest_exp='-k python2'
    - make integration-tests-testing-correctness-tests-resilience-all debug=true resilience=on pytest_exp='-k python3'
    - make integration-tests-testing-correctness-tests-topology-all debug=true resilience=on pytest_exp='-k python2'
    - make integration-tests-testing-correctness-tests-topology-all debug=true resilience=on pytest_exp='-k python3'

task:
  name: "correctness-tests"
  install_script:
    - .cirrusci/clone_tracker.sh
  test_script:
    - ulimit -c unlimited
    - ulimit -a
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true pytest_exp='-k pony'
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true pytest_exp='-k python2'
    - make integration-tests-testing-correctness-tests-autoscale-all debug=true pytest_exp='-k python3'
    - make integration-tests-testing-correctness-tests-topology-all debug=true pytest_exp='-k python2'
    - make integration-tests-testing-correctness-tests-topology-all debug=true pytest_exp='-k python3'
