#!/usr/bin/env python3

import asyncore
import asynchat
import os
import random
import re
import socket
import struct
import sys
import time
import traceback

# NOTES:
#
# 1. This server will truncate the out_path & out_path+".txnlog" files.
#    If you want to preserve their data, then move them out of the way
#    before starting this server.

from wallaroo.experimental import connector_wire_messages as cwm

def parse_abort_rules(path):
    a = []
    try:
        with open(path, 'rb') as f:
            for l in f:
                a.append(eval(l))
        return a
    except FileNotFoundError:
        return []

def reload_phase1_txn_state(path):
    txn_state = {}
    try:
        with open(path, 'rb') as f:
            for l in f:
                a = eval(l)
                if a[1] == '1-ok':
                    txn_state[a[2]] = (True, a[3])
                if a[1] == '1-rollback':
                    txn_state[a[2]] = (False, a[3])
                if (a[1] == '2-ok') or (a[1] == '2-rollback'):
                    del txn_state[a[2]]
    except FileNotFoundError:
        True
    return txn_state

def look_for_forced_abort(path):
    res = True # res will become self._txn_commit_next's value
    try:
        with open(path, 'rb') as f:
            for l in f:
                a = eval(l)
                if a[1] == 'next-txn-force-abort':
                    res = False
                elif a[1] == '1-ok':
                    if res == False:
                        print('FATAL ERROR: next-txn-force-abort followed by 1-ok')
                        sys.exit(66)
                    res = True
                elif a[1] == '1-rollback':
                    res = True
        return res
    except FileNotFoundError:
        return False

class AsyncServer(asynchat.async_chat, object):
    def __init__(self, handler_id, sock, out_path, abort_rule_path, streams=None):
        print("AsyncServer.__init__", handler_id, sock)
        self._id = handler_id
        self._conn = sock
        self._out_path = out_path
        self._out = open(self._out_path, 'ab')
        self._out_offset = self._out.tell()
        print('DBG: top of AsyncServer self._out_offset = {}'.format(self._out_offset))
        txn_log_path = self._out_path + ".txnlog"
        self._txn_log = open(txn_log_path, 'ab')
        self._abort_rule_path = abort_rule_path
        asynchat.async_chat.__init__(self, sock=self._conn)
        self.in_buffer = []
        self.out_buffer = []
        self.reading_header = True
        self.set_terminator(4) # first frame header
        self.in_handshake = True
        self._streams = {} if streams is None else streams
        self.received_count = 0
        self._reset_count = {}
        self._using_2pc = True
        self._txn_state = {}
        self._txn_stream_content = []
        self._txn_local_count = 0
        self._next_txn_force_abort_written = False

        self._abort_rules = parse_abort_rules(self._abort_rule_path)
        for t in self._abort_rules:
            if t[0] == "stream-content":
                stream_id = t[1]
                regexp = t[2]
                self._txn_stream_content.append((stream_id, regexp))
                # NOTE: This type doesn't have extended disconnect control!

        self._txn_state = reload_phase1_txn_state(txn_log_path)
        print('DBG: restored txn state: {}'.format(self._txn_state))
        self._txn_commit_next = look_for_forced_abort(txn_log_path)
        print('2PC: top: self._txn_commit_next = {}'.format(self._txn_commit_next))

    def collect_incoming_data(self, data):
        """Buffer the data"""
        self.in_buffer.append(data)

    def found_terminator(self):
        """Data is going to be in two parts:
        1. a 32-bit unsigned integer length header
        2. a payload of the size specified by (1)
        """
        if self.reading_header:
            # Read the header and set the terminator size for the payload
            self.reading_header = False
            h = struct.unpack(">I", b"".join(self.in_buffer))[0]
            self.in_buffer = []
            self.set_terminator(h)
        else:
            # Read the payload and pass it to _handle_frame
            frame_data = b"".join(self.in_buffer)
            self.in_buffer = []
            self.set_terminator(4) # read next frame header
            self.reading_header = True
            self._handle_frame(frame_data)

    def _handle_frame(self, frame):
        self.update_received_count()
        msg = cwm.Frame.decode(frame)
        # Hello, Ok, Error, Notify, NotifyAck, Message, Ack, Restart
        self.count = 0
        if isinstance(msg, cwm.Hello):
            if msg.version != "v0.0.1":
                print('FATAL ERROR: bad protocol version: {}'.format(msg.version))
                sys.exit(66)
            if msg.cookie != "Dragons Love Tacos!":
                print('FATAL ERROR: bad cookie: {}'.format(msg.cookie))
                sys.exit(66)
            # As of 2019-03-04, Wallaroo's connector sink is not managing
            # credits and will rely solely on TCP backpressure for its
            # own backpressure signalling.
            ok = cwm.Ok(500, self._streams.values())
            self.write(ok)
        elif isinstance(msg, cwm.Notify):
            if msg.stream_id != 1:
                error = cwm.Error("Unsupported stream id {}".format(msg.stream_id))
                self.write(error)
                return
            # respond with notifyack
            try:
                por = self._streams[msg.stream_id][2]
            except:
                por = 0
            notify_ack = cwm.NotifyAck(
                True,
                msg.stream_id,
                por)
            self._streams[msg.stream_id] = [msg.stream_id,
                                            msg.stream_name,
                                            por]
            self.write(notify_ack)
        elif isinstance(msg, cwm.Message):
            self.handle_message(msg)
        elif isinstance(msg, cwm.Error):
            # Got error message from worker
            # close the connection and pass msg to the error handler
            print("Received an error message. closing the connection")
            self.close()
            raise Exception(msg.message)
        else:
            # write the original message back
            self.write(msg)

    def handle_message(self, msg):
        if msg.stream_id == 0:
            self.handle_message_stream0(msg)
        else:
            self.handle_message_streamx(msg)

    def handle_message_stream0(self, msg):
        msg2 = cwm.TwoPCFrame.decode(msg.message)
        if isinstance(msg2, cwm.ListUncommitted):
            uncommitted = list(self._txn_state.keys())
            uncommitted.append("doesnt.exist.txn.aborting-wont-hurt.-----0-0")
            reply = cwm.ReplyUncommitted(msg2.rtag, uncommitted)
            reply_bytes = cwm.TwoPCFrame.encode(reply)
            msg = cwm.Message(0, cwm.Message.Ephemeral, None, None, None, reply_bytes)
            self.write(msg)
            print('2PC: ListUncommitted resp: {}'.format(reply))

            self.log_it(['list-uncommitted', uncommitted])
        elif isinstance(msg2, cwm.TwoPCPhase1):
            print('2PC: Phase 1 got {}'.format(msg2))
            print('2PC: Phase 1 txn_state = {}'.format(self._txn_state))

            # Sanity checks
            for (stream_id, start_por, end_por) in msg2.where_list:
                if stream_id != 1:
                    self._txn_commit_next = False
                    print('2PC: Phase 1 invalid stream_id {} in {}'
                        .format(stream_id, msg2))
                if start_por > end_por:
                    self._txn_commit_next = False
                    print('2PC: Phase 1 invalid start_por {} end_por {}'
                        .format(start_por, end_por))
                if end_por > self._out_offset:
                    self._txn_commit_next = False
                    print('2PC: Phase 1 invalid end_por {} file size {}'
                        .format(end_por, self._out.tell()))

            # Check local debugging/testing abort rules
            self._txn_local_count += 1
            close_before = False
            close_after = False
            for r in self._abort_rules:
                if r[0] == 'local-txn':
                    if self._txn_local_count == r[1]:
                        self._txn_commit_next = False
                        print('2PC: abort next transaction: local txn count {}'
                            .format(self._txn_local_count))
                        try:
                            success = r[2]
                            close_before = r[3]
                            close_after = r[4]
                        except:
                            True
                elif r[0] == 'txnid-regexp':
                    if re.search(r[1], msg2.txn_id):
                        self._txn_commit_next = False
                        print('2PC: abort next transaction: regexp {} matches txn_id {}'
                            .format(r[1], msg2.txn_id))
                        try:
                            success = r[2]
                            close_before = r[3]
                            close_after = r[4]
                        except:
                            True

            self.flush_fsync(self._out)
            self.flush_fsync(self._txn_log)
            success = self._txn_commit_next

            self._txn_state[msg2.txn_id] = (success, msg2.where_list)
            if success:
                log_tag = '1-ok'
            else:
                log_tag = '1-rollback'
            self.log_it([log_tag, msg2.txn_id, msg2.where_list])

            if close_before:
                self.log_it(['close', 'before reply'])
                self.close()
                return

            reply = cwm.TwoPCReply(str(msg2.txn_id).encode('utf-8'), success)
            reply_bytes = cwm.TwoPCFrame.encode(reply)
            msg = cwm.Message(0, cwm.Message.Ephemeral, None, None, None, reply_bytes)
            self.write(msg)

            self._txn_commit_next = True
            self._next_txn_force_abort_written = False

            if close_after:
                self.log_it(['close', 'after reply'])
                self.close()
                return
        elif isinstance(msg2, cwm.TwoPCReply):
            raise Exception("Bad stream ID 0 message: {}".format(msg2))
        elif isinstance(msg2, cwm.TwoPCPhase2):
            print('2PC: Phase 2 got {}'.format(msg2))
            print('2PC: Phase 2 pre txn_state = {}'.format(self._txn_state))
            if msg2.txn_id in self._txn_state:
                (phase1_status, where_list) = self._txn_state[msg2.txn_id]
                if not msg2.commit:
                    for (stream_id, start_por, end_por) in where_list:
                        if stream_id != 1:
                            raise Exception('Phase 2 abort: bad stream_id {}'.
                                format(stream_id))
                        print('2PC: truncating {} to offset {}'.format(self._out_path, start_por))
                        self._out.truncate(start_por)
                        self.flush_fsync(self._out)
                        self._out_offset = start_por
                        self._streams[stream_id][2] = start_por

                if not phase1_status and msg2.commit:
                    print('2PC: mute/unmute placeholder 1 @ aloc_sink')
                    print('2PC: Protocol error: phase 1 status was rollback but phase 2 says commit')
                    ##### time.sleep(1.0)
                    print('2PC: mute/unmute placeholder 2 @ aloc_sink')
                    sys.exit(66)

                if msg2.commit and phase1_status:
                    log_tag = '2-ok'
                    offset = where_list[0][2]
                else:
                    log_tag = '2-rollback'
                    offset = where_list[0][1]
                self.log_it([log_tag, msg2.txn_id, offset])

                del self._txn_state[msg2.txn_id]
                print('2PC: Phase 2 post txn_state = {}'.format(self._txn_state))
            else:
                print('2PC: ERROR: Phase 2 got unknown txn_id {} commit {}'.format(msg2.txn_id, msg2.commit))
                self.log_it(['2-error', msg2.txn_id, msg2.commit])
            # No reply is required for Phase 2
        else:
            raise Exception("Stream ID 0 not implemented, msg2 = {}".format(msg2))

    def handle_message_streamx(self, msg):
        bs = bytes(msg.message)

        for (stream_id, regexp) in self._txn_stream_content:
            if stream_id == msg.stream_id:
                if re.search(regexp, str(bs)):
                    self._txn_commit_next = False
                    print('2PC: abort next transaction: {} matches {}'
                        .format(regexp, bs))

        if msg.message_id != None:
            if self._out_offset == msg.message_id:
                ret1 = self._out.write(bs)
                if len(bs) != ret1:
                    self._txn_commit_next = False
                    raise Exception("File write error? {} != {} or {} != None".format(len(bs), ret1, ret2))
                self._out_offset += len(msg.message)
                self._streams[msg.stream_id][2] = msg.message_id
                print('DBG: _out_offset is now {}'.format(self._out_offset))
            elif self._out_offset < msg.message_id:
                m = 'ERROR: MISSING DATA: self._out_offset {} < msg.message_id {}'.format(self._out_offset, msg.message_id)
                self._txn_commit_next = False
                if not self._next_txn_force_abort_written:
                    print(m)
                    self._next_txn_force_abort_written = True
                    self.log_it(['next-txn-force-abort', m])
            elif self._out_offset > msg.message_id:
                print('ERROR: duplicate data: self._out_offset {} > msg.message_id {}'.format(self._out_offset, msg.message_id))
        else:
            print('FATAL ERROR: message has no message_id')
            sys.exit(66)

        if msg.flags & cwm.Message.Eos:
            # ack eos
            print("NH: acking eos for {}".format(msg))
            self.write(cwm.Ack(credits = 1,
                               acks= [(msg.stream_id, self._streams[msg.stream_id][2])]))

    def write(self, msg):
        print("write {}".format(msg))
        data = cwm.Frame.encode(msg)
        super(AsyncServer, self).push(data)

    def update_received_count(self):
        self.received_count += 1
        if (not self._using_2pc) and self.received_count % 3 == 0:
            print("Sending ack for streams!")
            ack = cwm.Ack(
                credits = 10,
                acks = [
                    (sid, por) for sid, _, por in self._streams.values()])
            print('DBG: send ack msg: {}'.format(ack))
            self.write(ack)
        if self.received_count % 9999200 == 0:
            # send a restart every 200 messages
            print('PERIODIC RESTART, what could possibly go wrong?')
            self.write(cwm.Restart())

    def handle_error(self):
        _type, _value, _traceback = sys.exc_info()
        traceback.print_exception(_type, _value, _traceback)

    def close(self):
        print("Closing the connection")
        print("last received id by stream:\n\t{}".format(
            "\n\t".join("{}, {}: {}".format(sid, sn, mid)
                      for sid, sn, mid in self._streams.values())))
        super(AsyncServer, self).close()
        self.log_it(['connection-closed', True])
        ### self._out.write(b'<DEBUG-ONLY-CONNECTION-CLOSED>\n')

    def flush_fsync(self, file):
        x = file.flush()
        if x:
            print('FATAL ERROR: flush failed: {}'.format(x))
            sys.exit(66)
        x = os.fsync(file.fileno())
        if x:
            print('FATAL ERROR: fsync failed: {}'.format(x))
            sys.exit(66)

    def log_it(self, log):
        log.insert(0, time.time())
        self._txn_log.write(bytes("{}\n".format(log).encode('utf-8')))
        self.flush_fsync(self._txn_log)

class EchoServer(asyncore.dispatcher):

    def __init__(self, host, port, out_path, abort_rule_path):
        asyncore.dispatcher.__init__(self)
        self.create_socket(family=socket.AF_INET, type=socket.SOCK_STREAM)
        self.set_reuse_addr()
        self.bind((host, port))
        self.listen(1)
        self._out_path = out_path
        self._abort_rule_path = abort_rule_path
        self.count = 0
        self._streams = {}

    def handle_accepted(self, sock, addr):
        print('Incoming connection from %s' % repr(addr))
        handler = AsyncServer(self.count, sock,
            self._out_path, self._abort_rule_path, self._streams)
        self.count += 1

out_path = sys.argv[1]
abort_rule_path = sys.argv[2]
print("out_path: ", out_path)
print ("abort_rule_path: ", abort_rule_path)
server = EchoServer('127.0.0.1', 7200, out_path, abort_rule_path)
print("server: ", server)
print("asyncore file: ", asyncore.__file__)
asyncore.loop(timeout=0.001)
